# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/fmabrouk/Documents/GitHub/AM_Radio_730KHz/AM_Radio_730KHz/AM_Radio_730KHz.cache/wt [current_project]
set_property parent.project_path C:/Users/fmabrouk/Documents/GitHub/AM_Radio_730KHz/AM_Radio_730KHz/AM_Radio_730KHz.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/fmabrouk/Documents/GitHub/AM_Radio_730KHz/AM_Radio_730KHz/AM_Radio_730KHz.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/fmabrouk/Documents/GitHub/AM_Radio_730KHz/VHDL/ADC_Interface.vhd
  C:/Users/fmabrouk/Documents/GitHub/DDS_AM_DEMODULATION_DAC/VHDL/AM_DeModulation_TopLevel.vhd
}
read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/clk_wiz_0_19/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/clk_wiz_0_19/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/clk_wiz_0_19/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/clk_wiz_0_19/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/dds_compiler_0_6/dds_compiler_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/dds_compiler_0_6/dds_compiler_0_ooc.xdc]

read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/mult_gen_0_2/mult_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/mult_gen_0_2/mult_gen_0_ooc.xdc]

read_ip -quiet C:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fir_compiler_0_2/fir_compiler_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fir_compiler_0_2/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fmabrouk/Documents/FPGA/FIR_SysGen/SysGenIP/ip/fir_compiler_0_2/fir_compiler_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/fmabrouk/Documents/GitHub/DDS_AM_Modulation_DAC/AM_Modulation/UltrScale_UCF.xdc
set_property used_in_implementation false [get_files C:/Users/fmabrouk/Documents/GitHub/DDS_AM_Modulation_DAC/AM_Modulation/UltrScale_UCF.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top AM_Radio_730_KHz_TopLevel -part xczu9eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AM_Radio_730_KHz_TopLevel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AM_Radio_730_KHz_TopLevel_utilization_synth.rpt -pb AM_Radio_730_KHz_TopLevel_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
